const ObjectsConstants = {
  OBJECTS_ADD_ASTEROID: "OBJECTS_ADD_ASTEROID",
  OBJECTS_ROTATE_SHIP: "OBJECTS_ROTATE_SHIP",
  OBJECTS_ROTATE_ONE: "OBJECTS_ROTATE_ONE",
  OBJECTS_CHANGE_SPEED: "OBJECTS_CHANGE_SPEED",
  OBJECTS_TICK: "OBJECTS_TICK",
};

export default ObjectsConstants;
