const ObjectsConstants = {
  OBJECTS_ADD_ASTEROID: "OBJECTS_ADD_ASTEROID",
  OBJECTS_ROTATE_SHIP: "OBJECTS_ROTATE_SHIP",
  OBJECTS_ACCELERATE_SHIP: "OBJECTS_ACCELERATE_SHIP",
  OBJECTS_SHOOT: "OBJECTS_SHOOT",
  OBJECTS_TICK: "OBJECTS_TICK",
  OBJECTS_RESIZE: "OBJECTS_RESIZE",
};

export default ObjectsConstants;
