const ObjectsConstants = {
  OBJECTS_ADD_ASTEROID: "OBJECTS_ADD_ASTEROID",
  OBJECTS_ROTATE_SHIP: "OBJECTS_ROTATE_SHIP",
  OBJECTS_ROTATE_SHIP: "OBJECTS_ACCELERATE_SHIP",
  OBJECTS_TICK: "OBJECTS_TICK",
};

export default ObjectsConstants;
