const ActionConstants = {
  OBJECTS_ADD_ASTEROID: "OBJECTS_ADD_ASTEROID",
  OBJECTS_ROTATE_SHIP: "OBJECTS_ROTATE_SHIP",
  OBJECTS_ACCELERATE_SHIP: "OBJECTS_ACCELERATE_SHIP",
  OBJECTS_SHOOT: "OBJECTS_SHOOT",
  OBJECTS_TICK: "OBJECTS_TICK",
  GAME_START: "GAME_START",
  GAME_PAUSE: "GAME_PAUSE",
  GAME_RESUME: "GAME_RESUME",
  GAME_TERMINATE: "GAME_TERMINATE",
};

export default ActionConstants;
